- name: Say HEY
  debug:
    msg: "HEY ! Welcome to the prerequisite playbook !"

- name: Add IP and DNS record in /etc/host file
  lineinfile:
    path: /etc/hosts
    line: "{{item.0}}"
    state: present
  tags:
    - dns records
  with_together:
    - "{{ip_dns_host_file}}"

- name: Disable SELinux
  selinux:
    state: disabled
  tags:
    - selinux disable

- name: Create kubernetes.repo file
  file:
    path: /etc/yum.repos.d/kubernetes.repo
    state: touch
    owner: root
    group: root
    mode: '0644'
  tags: 
    - create kubernetes repo file

- name: Create docker-ce.repo file
  file:
    path: /etc/yum.repos.d/docker-ce.repo
    state: touch
    owner: root
    group: root
    mode: '0644'
  tags:
    - create docker-ce repo file

- name: Insert configuration in kubernetes.repo file
  blockinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  tags:
    - repo content k8s

- name: Insert configuration in docker.repo file
  blockinfile:
    path: /etc/yum.repos.d/docker-ce.repo
    block: |
      [docker-ce-stable]
      name=Docker CE Stable - $basearch
      baseurl=https://download.docker.com/linux/centos/$releasever/$basearch/stable
      enabled=1
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/centos/gpg

      [docker-ce-stable-debuginfo]
      name=Docker CE Stable - Debuginfo $basearch
      baseurl=https://download.docker.com/linux/centos/$releasever/debug-$basearch/stable
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/centos/gpg

      [docker-ce-stable-source]
      name=Docker CE Stable - Sources
      baseurl=https://download.docker.com/linux/centos/$releasever/source/stable
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/centos/gpg

      [docker-ce-test]
      name=Docker CE Test - $basearch
      baseurl=https://download.docker.com/linux/centos/$releasever/$basearch/test
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/centos/gpg

      [docker-ce-test-debuginfo]
      name=Docker CE Test - Debuginfo $basearch
      baseurl=https://download.docker.com/linux/centos/$releasever/debug-$basearch/test
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/centos/gpg

      [docker-ce-test-source]
      name=Docker CE Test - Sources
      baseurl=https://download.docker.com/linux/centos/$releasever/source/test
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/centos/gpg

      [docker-ce-nightly]
      name=Docker CE Nightly - $basearch
      baseurl=https://download.docker.com/linux/centos/$releasever/$basearch/nightly
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/centos/gpg

      [docker-ce-nightly-debuginfo]
      name=Docker CE Nightly - Debuginfo $basearch
      baseurl=https://download.docker.com/linux/centos/$releasever/debug-$basearch/nightly
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/centos/gpg

      [docker-ce-nightly-source]
      name=Docker CE Nightly - Sources
      baseurl=https://download.docker.com/linux/centos/$releasever/source/nightly
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/centos/gpg
  tags:
    - repo content docker

- name: Update all packages
  yum:
    name: '*'
    state: latest
  tags: update all packages

- name: Install Kubeadm and Docker
  yum: 
    name: "{{item.0}}"
    state: latest
  with_together:
    - "{{packages}}"
  tags: install packages

- name: Enable docker systemd
  systemd:
    name: docker
    enabled: yes
    state: started
  tags: start docker

- name: Enable kubelet systemd
  systemd:
    name: kubelet
    enabled: yes
    state: started
  tags: start kubelet

- name: Disable swap
  shell: "swapoff -a"
  tags: disable swap

- name: Pause for 30 sec
  pause:
    secondes: 30
  tags: pause
